### ISSUE TITLE
Install OAuth Client in DM Server

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/DM#73] opened 2017-04-05 18:58 UTC
@gremid Am I correct that this would replace the HTTP basic auth we have in place, and that it would not otherwise change how users and their data are managed once authenticated? So system-wide and per-project authorizations are still handled internally by DM, and would continue to work as they do now once OAuth authentication is implemented. Thanks!

**Comment by gremid** [comment] 2017-07-13 12:46
Logging into DM now works via external authentication providers: Google, GitHub and Perfomant's own service are configured on the staging server for this purpose. Authorization of access to specific projects still happens within DM.

**How to test**

1. Log into DM via any of the providers.
1. Create a new project for which you are subsequently granted admin rights as its creator, or open one for which you have admin rights already.
1. Assign access rights to some other user who has logged into DM before by selecting her account in the "Project Info And Sharing" dialog, checking boxes for the desired access rights and clicking "Save".
1. Ask the other user to log into and/or reload DM, checking whether access to the specific project has been granted.

**Comment by SteveMarvin** [comment] 2017-07-13 17:32
I don't think this is ready for release, I'm afraid. 

I can sign up and log into the app via Performant, Google or GitHub, although the authorization screens are incredibly scary.

![screen shot 2017-07-13 at 10 46 18 am](https://user-images.githubusercontent.com/18423533/28175131-5e687412-67c1-11e7-92a6-4ecb37ff42f4.png)
![screen shot 2017-07-13 at 10 57 44 am](https://user-images.githubusercontent.com/18423533/28175139-613a3086-67c1-11e7-971f-311d62ababab.png)

But once I'm in, things bog down. 

When I log in via Performant, I am clearly logging into the account I have been using for some time; I see my own GoT project and the others usually available. 

When I try to add my Google and GitHub logins to my GoT project, they do not come up in the "Add Member" search tool. I have to realize that the GitHub login is using null null for my name instead of my actual name. If I enter "null" into the search tool, it shows both Andy and my accounts with names of "null null", and I can add them. However, typing part or all of my email address used in my GitHub login does not bring any results. When logged in with my GitHub account, this is how it presents me in the list of users:

![screen shot 2017-07-13 at 1 23 08 pm](https://user-images.githubusercontent.com/18423533/28179014-a04e2ee6-67ce-11e7-8537-18daf2465ae2.png)

The Google login presents me as this:

![screen shot 2017-07-13 at 1 23 34 pm](https://user-images.githubusercontent.com/18423533/28179002-90d1c2b6-67ce-11e7-8c79-7a4ef417ed82.png)

And nothing will bring that account up when trying to add it to another login's project. "People" brings up nothing, and pasting in that long number does nothing, either. 

Unless I am misunderstanding the intended functionality, I don't think this is ready.

**Comment by gremid** [comment] 2017-07-14 11:04
@SteveMarvin: Thanks for thoroughly testing this!

## Scary Authorization Requests from GitHub and Performant

@akstuhl and I tried to make the procedure less scary: Performant's provider does not ask for authorization at all anymore (given that we set up the provider specifically for DM), GitHub should only ask for read-only access to profile and e-mail data now:

![dm-github-oauth-scope](https://user-images.githubusercontent.com/695757/28209399-a41863a6-6892-11e7-979a-a6478db865cb.png)

Should you like to reproduce this, open your GitHub settings and revoke the already granted access for the "DM - Staging" application, listed under "Authorized OAuth Apps".

## Incomplete Account Data (`null`)

I assumed wrongly that a user's full name is a required field in GitHub profiles. As this is not the case, `null` was given for missing display/full names. I fixed that by using the GitHub profile name as the default.

(@akstuhl and you should log into DM via GitHub again, so the `null` values get overwritten with the new defaults.)

## Looking up Users in the Authorization Dialog

The user's key (i.e. `google:people:1234567` or `github:xyz`) is not incorporated as a search field in the dropdown box for adding users to a project. The full name and the e-mail address of a user is though. So you should get results when searching for "steve" or "jamie" or "performant" unless Jamie, you or all registered accounts with e-mails at performantsoftware.com have already been assigned to the project ( the search hits are filtered by removing all accounts from the dropdown list which already present in the permission table).

## Missing Accounts in the Authorization Dialog

While testing, please note that existing accounts are migrated on the fly based on matching e-mail addresses. Suppose you log into DM via Google with an associated e-mail address `me@mail.com` and later log into DM again via e.g. GitHub, having the same address associated with your GitHub profile, your Google-based account is migrated to the GitHub profile automatically. So you should not find the Google-based account anymore but have inherited all its permissions.

**Comment by SteveMarvin** [comment] 2017-07-18 17:59
**Scary Authorizations**: Look great! New GitHub account login generated far less scary results.
**Incomplete Account Data**: Seems to be good now. Names showing up.
**Looking Up Users**: Much better, Google now showing up. However, it is also displaying @github.local emails, as well as the email address the github users registered with.
**Missing Accounts**: Understood. 
Overall, marking this as ACCEPTED, and I'll add the github.local thing as a bug.

**Closed as completed** 2017-09-18 20:30 UTC
