### ISSUE TITLE
Weirdness upon save

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/DM#47] opened 2016-11-09 16:20 UTC
Description from Heather, via Martin. This supersedes my solution from December.

> I worked on 18 inscriptions in the developer site (dm.performantsoftware.com) from about 4:50 pm to 5:10 pm (Central Standard Time) on December 21.  For the first nine that I did, I entered my data so that the inscription would save.  And it did.  For the next seven, I entered the data so that the annotation would not save. And it did not.  Then I switched back to the first method for the last two annotations and they indeed saved. 
> 
> This is the difference between saving and not saving:
> 
> In both cases, the title changes usually save regardlesss.  But...
> 
> 1) if I start by making changes in the title, then make changes in the annotation text, the annotation does not save.
> 
> 2) if I start by making changes in the annotation text, and then make changes in the title, the annotation will save.

[EDIT, 4/13/2017, from Martin]

Heather reports that she is occasionally still discovering annotations that have been made that are missing and have to be redone. Not a massive amount - only a handful, but that there still seem to be some annotation work that is failing to be saved.

**Comment by jamiefolsom** [comment] 2016-12-13 23:55
I believe this was due to a character which may be common in transcriptions, but which was not being escaped by the client side RDF lexer, N3.js: the \&middot; character: "&middot;".

Here's an excerpt of the server logs showing the pattern

```
2016-12-08 20:30:06 SEVERE [org.apache.jena.riot.system.ErrorHandlerFactory$ErrorLogger logError] [line: 21, col: 1 ] Broken token (newline): <p class="p1"><b>Transcription: </b><span class="s1">Ar</span><span class="s2">ſ</span><span class="s1">uoe </span><span class="s2">·</span><span class="s1"> ciuit(as) </span><span class="s2">·</span></p>

2016-12-08 20:52:53 SEVERE [org.apache.jena.riot.system.ErrorHandlerFactory$ErrorLogger logError] [line: 21, col: 1 ] Broken token (newline): <p class="p1"><b>Transcription: </b>Hic · barbari · getuli · natabreſ · (et) garamanteſ · habitant · </p>

2016-12-08 20:53:32 SEVERE [org.apache.jena.riot.system.ErrorHandlerFactory$ErrorLogger logError] [line: 21, col: 1 ] Broken token (newline): <p class="p1"><b>Transcription: </b><span class="s1">Philli </span><span class="s2">· pudiciam vxorum p(ro)bant · obiectu nouiter nator(um) ſerpentib(us) ·</span></p>
```

Note that all three of those errors contains a \&middot; character.

I've deployed a fix to staging; test it at http://67.207.158.85/ by using that character.

**Comment by SteveMarvin** [comment] 2016-12-15 15:58
Seems to handle it OK now. I don't know what the original weirdness looked like exactly...but it seems to be fine now.

**Comment by gremid** [comment] 2017-07-13 13:11
Same here, cannot reproduce the specific issue. Closing for now.

**Closed as completed by gremid** 2017-07-13 13:11 UTC
Labels: Server Side
