### ISSUE TITLE
Endless progress spinner

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/DM#4] opened 2016-08-02 18:23 UTC
When re-opening a newly created project, it appears to load, but a progress spinner runs endlessly in the center of the image. Even though prior annotations are visible and usable, the spinner never finishes.

**Comment by gremid** [comment] 2016-08-30 14:16
Also assumed to be a duplicate of #10.

**Comment by SteveMarvin** [comment] 2016-08-30 15:38
No longer reproducible. 👍

**Closed as completed** 2016-09-02 10:31 UTC
Labels: bug
